apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbgpod
  labels:
    app: dbg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dbg
  template:
    metadata:
      labels:
        app: dbg
    spec:
      containers:
      - name: dbgcontainer
        image: trausch/dbg:v1

