apiVersion: v1
kind: Pod
metadata:
  name: hellopod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:trusty
    command: ["/bin/bash", "-ec", "while :; do echo 'Hello from the pod universe'; sleep 5; done"]
  restartPolicy: Never
